<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Create</title>
    <link rel="stylesheet" href="/css/style.css">
</head>
<body>
<span>Time Restriction :</span> <input id="time_restriction" type="text"/> <BR>
<span>Views Restriction :</span> <input id="views_restriction" type="text"/><BR>
<textarea id="code_snippet" class="snippet">// write your code here</textarea>
<br>
<button id="send_snippet" type="submit" onclick="send();">Submit</button>
<script src="/postCode.js"></script>
</body>
</html>